-- ============================================================
-- V1 - Baseline schema
-- Enterprise Multi-Tenant Asset and Task Management Platform
-- ============================================================

-- ============================================================
-- ORGANIZATIONS
-- ============================================================

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(150) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT uk_organizations_name
        UNIQUE (name)
);

CREATE INDEX idx_organization_name
    ON organizations (name);


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    email VARCHAR(150) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    organization_id BIGINT NOT NULL,

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT users_role_check
        CHECK (
            role IN (
                'ORGANIZATION_ADMIN',
                'PROJECT_MANAGER',
                'TEAM_MEMBER'
            )
        ),

    CONSTRAINT fk_users_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
);

CREATE INDEX idx_user_email
    ON users (email);

CREATE INDEX idx_user_organization
    ON users (organization_id);


-- ============================================================
-- PROJECTS
-- ============================================================

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(1000),
    name VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    manager_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,

    CONSTRAINT projects_status_check
        CHECK (
            status IN (
                'ACTIVE',
                'ARCHIVED',
                'COMPLETED'
            )
        ),

    CONSTRAINT fk_projects_manager
        FOREIGN KEY (manager_id)
        REFERENCES users(id),

    CONSTRAINT fk_projects_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
);

CREATE INDEX idx_project_manager
    ON projects (manager_id);

CREATE INDEX idx_project_organization
    ON projects (organization_id);

CREATE INDEX idx_project_status
    ON projects (organization_id, status);


-- ============================================================
-- TASKS
-- ============================================================

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(2000),
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    assignee_id BIGINT,
    organization_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    due_date DATE,

    CONSTRAINT tasks_priority_check
        CHECK (
            priority IN (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT tasks_status_check
        CHECK (
            status IN (
                'BACKLOG',
                'IN_PROGRESS',
                'IN_REVIEW',
                'COMPLETED'
            )
        ),

    CONSTRAINT fk_tasks_assignee
        FOREIGN KEY (assignee_id)
        REFERENCES users(id),

    CONSTRAINT fk_tasks_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id),

    CONSTRAINT fk_tasks_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
);

CREATE INDEX idx_task_assignee
    ON tasks (assignee_id);

CREATE INDEX idx_task_created_at
    ON tasks (organization_id, created_at);

CREATE INDEX idx_task_organization
    ON tasks (organization_id);

CREATE INDEX idx_task_priority
    ON tasks (organization_id, priority);

CREATE INDEX idx_task_project
    ON tasks (project_id);

CREATE INDEX idx_task_status
    ON tasks (organization_id, status);


-- ============================================================
-- AUDIT LOGS
-- ============================================================

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    details VARCHAR(2000),
    entity_id BIGINT,
    entity_type VARCHAR(100),
    actor_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,

    CONSTRAINT audit_logs_action_check
        CHECK (
            action IN (
                'ORGANIZATION_CREATED',
                'USER_CREATED',
                'USER_ACTIVATED',
                'USER_SUSPENDED',
                'PROJECT_CREATED',
                'PROJECT_UPDATED',
                'PROJECT_ARCHIVED',
                'TASK_CREATED',
                'TASK_UPDATED',
                'TASK_ASSIGNED',
                'TASK_STATUS_CHANGED'
            )
        ),

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_id)
        REFERENCES users(id),

    CONSTRAINT fk_audit_logs_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
);

CREATE INDEX idx_audit_action
    ON audit_logs (organization_id, action);

CREATE INDEX idx_audit_actor
    ON audit_logs (actor_id);

CREATE INDEX idx_audit_created_at
    ON audit_logs (organization_id, created_at);

CREATE INDEX idx_audit_organization
    ON audit_logs (organization_id);